AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/FrozenStringLiteralComment:
 Enabled: false

Style/Documentation:
 Enabled: false

Style/GlobalVars:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

EndOfLine:
  Enabled: false

Layout/LineLength:
 Max: 260

Metrics/MethodLength:
 Max: 30

Metrics/AbcSize:
 Max: 25

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10
